services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    environment:
    - PYTHONPATH=/app
    volumes:
    - ./app:/app
    ports:
    - 8000:8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    command: python hello.py
