services:
  db:
    image: postgres:14
    ports:
    - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    - ./sql/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      POSTGRES_DB: vtb
      POSTGRES_USER: vtb
      POSTGRES_PASSWORD: vtb
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
    - 8000:8000
    volumes:
    - ./app:/app/app
    environment:
      PYTHONPATH: /app
      POSTGRES_HOST: db
      POSTGRES_DB: vtb
      POSTGRES_USER: vtb
      POSTGRES_PASSWORD: vtb
    depends_on:
    - db   # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
      #command: python app/hello.py
