services:
  db:
    image: postgres:14
    ports:
    - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    - ./sql/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    env_file: docker/.env.local
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
    - 8000:8000
    volumes:
    - ./service_api:/app/app
    env_file: docker/.env.local
    depends_on:
    - db
  scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile.scraper
    volumes:
    - ./service_scraper:/app/app
    env_file: docker/.env.local
    depends_on:
    - db
  aggregator:
    build:
      context: .
      dockerfile: docker/Dockerfile.aggregator
    volumes:
    - ./service_aggregator:/app/app
    env_file: docker/.env.local
    depends_on:
    - db
  insights:
    image: vladislavkruglikov/insights:master
    volumes:
      - ./service_insights:/app/app
    env_file: docker/.env.local
    tty: true
    command: "/bin/bash"
    depends_on:
      - db
  filterer:
    build:
      context: .
      dockerfile: docker/Dockerfile.filterer
    volumes:
      - ./service_filterer:/app/app
    env_file: docker/.env.local
    tty: true
    command: "/bin/bash"
    depends_on:
      - db
