services:
  db:
    image: postgres:14
    ports:
    - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    - ./sql/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    env_file: docker/.env
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
    - 8000:8000
    volumes:
    - ./app:/app/app
    env_file: docker/.env
    depends_on:
    - db
  scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile.scraper
    volumes:
    - ./app:/app/app
    env_file: docker/.env
    depends_on:
    - db
  aggregator:
    build:
      context: .
      dockerfile: docker/Dockerfile.aggregator
    volumes:
    - ./app:/app/app
    env_file: docker/.env
    depends_on:
    - db
