FROM python:3.9-slim

ENV APP_HOME=/app

WORKDIR $APP_HOME

COPY requirements_aggregator.txt .
RUN pip install --no-cache-dir -r requirements_aggregator.txt

COPY ./aggregator $APP_HOME

CMD ["python", "/app/hello.py"]
