FROM python:3.9-slim

ENV APP_HOME=/app

WORKDIR $APP_HOME

RUN apt-get update

COPY requirements_filterer.txt .

RUN pip install --no-cache-dir -r requirements_filterer.txt

ADD ./resources $APP_HOME/resources
ADD ./service_filterer $APP_HOME/service_filterer

ENV PYTHONPATH=${PYTHONPATH}:$PWD

CMD ["uvicorn", "service_filterer.main:app", "--host", "0.0.0.0", "--port", "8000"]
