FROM python:3.9-slim

ENV APP_HOME=/app

WORKDIR $APP_HOME

RUN apt-get update

COPY requirements_filterer.txt .

RUN pip install --no-cache-dir -r requirements_filterer.txt

ADD ./service_insights $APP_HOME/requirements_filterer

ENV PYTHONPATH=${PYTHONPATH}:$PWD
