FROM python:3.9-slim

ENV APP_HOME=/app

WORKDIR $APP_HOME

COPY requirements_scraper.txt .
RUN pip install --no-cache-dir -r requirements_scraper.txt

COPY ./service_scraper $APP_HOME

CMD ["python", "/app/hello.py"]
