FROM python:3.9-slim

ENV APP_HOME=/app

WORKDIR $APP_HOME

COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt

COPY ./service_api $APP_HOME/app
COPY ./service_api/static $APP_HOME/static

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
